version: '3'

services:

  app:
    image: filipebastos/nodejs:latest
    container_name: nodejs
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    networks:
      - fullcyclenet

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/storage:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullcyclenet
    ports:
      - "3306:3306"

  reverse-proxy:
    image: filipebastos/nginx:latest
    container_name: nginx
    networks:
      - fullcyclenet
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  fullcyclenet:
    driver: bridge
